# Generated by Django 6.0.2 on 2026-05-13 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('menstrual_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='patients.menstrualcycle')),
            ],
        ),
    ]
