# Generated by Django 6.0.2 on 2026-03-03 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pregnancies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('POIDS', 'Poids'), ('TENSION', 'Tension'), ('GLYCEMIE', 'Glycémie'), ('TEMPERATURE', 'Température')], default='POIDS', max_length=50)),
                ('measurement_date', models.DateTimeField()),
                ('value1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('value2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('unit', models.CharField(choices=[('KG', 'kg'), ('MMHG', 'mmHg'), ('G_L', 'g/L'), ('C', '°C')], max_length=10)),
                ('context', models.CharField(blank=True, default='', max_length=100)),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='woman', to='Pregnancies.pregnancy')),
            ],
        ),
    ]
