# Generated by Django 6.0.2 on 2026-03-03 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pregnancies', '0001_initial'),
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='pregnancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_id', to='Pregnancies.pregnancy'),
        ),
    ]
