# Generated by Django 6.0.2 on 2026-03-03 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pregnancies', '0002_alter_pregnancy_patient'),
        ('measurements', '0002_alter_measurement_pregnancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='pregnancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='Pregnancies.pregnancy'),
        ),
    ]
