# Generated by Django 6.0.2 on 2026-03-08 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pregnancies', '0002_alter_pregnancy_patient'),
        ('measurements', '0003_alter_measurement_pregnancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='measurement_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='type',
            field=models.CharField(choices=[('WEIGHT', 'Weight'), ('BLOOD_PRESSURE', 'Blood Pressure'), ('GLYCEMIA', 'Glycemia'), ('TEMPERATURE', 'Temperature'), ('HEART_RATE', 'Heart Rate'), ('OXYGEN', 'Oxygen')], max_length=50),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='unit',
            field=models.CharField(choices=[('KG', 'kg'), ('MMHG', 'mmHg'), ('G_L', 'g/L'), ('C', '°C'), ('BPM', 'bpm')], max_length=10),
        ),
    ]
