# Generated by Django 6.0.2 on 2026-03-08 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pregnancies', '0002_alter_pregnancy_patient'),
        ('measurements', '0004_alter_measurement_measurement_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('global_risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('global_risk_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('personal_risk_level', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10, null=True)),
                ('personal_risk_note', models.TextField(blank=True, null=True)),
                ('glucose_used', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bp_sys_used', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bp_dia_used', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('heart_rate_used', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight_used', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='Pregnancies.pregnancy')),
            ],
        ),
    ]
