# Generated by Django 6.0.2 on 2026-03-31 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0006_remove_measurement_pregnancy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskassessment',
            name='global_risk_percentage',
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='body_temp_used',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
