# Generated by Django 6.0.2 on 2026-05-07 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0007_remove_riskassessment_global_risk_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='final_risk_level',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10, null=True),
        ),
    ]
