# Generated by Django 6.0.2 on 2026-03-03 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pregnancies', '0002_alter_pregnancy_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('REPORT', 'Report'), ('ULTRASOUND', 'Ultrasound')], max_length=30)),
                ('file', models.FileField(upload_to='attachments/')),
                ('upload_date', models.DateTimeField(auto_now=True)),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='Pregnancies.pregnancy')),
            ],
        ),
    ]
