# Generated by Django 6.0.2 on 2026-03-08 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_files', '0001_initial'),
        ('patients', '0002_alter_patient_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='pregnancy',
        ),
        migrations.AddField(
            model_name='attachment',
            name='patient',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='patients.patient'),
            preserve_default=False,
        ),
    ]
