# Generated by Django 6.0.2 on 2026-05-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_files', '0003_patientdoctoraccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdoctoraccess',
            name='can_write',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientdoctoraccess',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
