# Generated by Django 6.0.2 on 2026-05-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_files', '0004_patientdoctoraccess_can_write_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(max_length=255, upload_to='attachments/'),
        ),
    ]
