# Generated by Django 6.0.2 on 2026-05-07 22:06

import medical_files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_files', '0005_alter_attachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(max_length=255, upload_to=medical_files.models.attachment_upload_path),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='type',
            field=models.CharField(choices=[('REPORT', 'Report'), ('ULTRASOUND', 'Ultrasound'), ('BLOOD_TEST', 'Blood Test'), ('URINE_TEST', 'Urine Test'), ('PRESCRIPTION', 'Prescription'), ('VACCINATION', 'Vaccination'), ('ECHO', 'Echocardiography'), ('OTHER', 'Other')], max_length=30),
        ),
    ]
