# Generated by Django 6.0.2 on 2026-05-07 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_doctor_consultation_duration'),
        ('medical_files', '0006_alter_attachment_file_alter_attachment_type'),
        ('patients', '0002_alter_patient_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdoctoraccess',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_accesses', to='doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='patientdoctoraccess',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_accesses', to='patients.patient'),
        ),
    ]
