# Generated by Django 6.0.2 on 2026-05-08 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_files', '0007_alter_patientdoctoraccess_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdoctoraccess',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted')], default='PENDING', max_length=20),
        ),
    ]
