# Generated by Django 6.0.2 on 2026-05-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_files', '0008_patientdoctoraccess_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdoctoraccess',
            name='granted_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
