# Generated by Django 6.0.2 on 2026-03-03 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DELAYED_PERIOD', 'Delayed Period'), ('HIGH_GLYCEMIA', 'High Glycemia'), ('LOW_GLYCEMIA', 'Low Glycemia'), ('HIGH_BLOOD_PRESSURE', 'High Blood Pressure'), ('LOW_BLOOD_PRESSURE', 'Low Blood Pressure'), ('APPOINTMENT_REMINDER', 'Appointment Reminder'), ('TREATMENT_REMINDER', 'Treatment Reminder'), ('ULTRASOUND_REMINDER', 'Ultrasound Reminder'), ('MEDICATION_REMINDER', 'Medication Reminder')], max_length=50)),
                ('message', models.TextField()),
                ('Status', models.CharField(choices=[('NEW', 'New'), ('READ', 'Read'), ('RESOLVED', 'Resolved')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
