# Generated by Django 6.0.2 on 2026-03-08 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='Status',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('DELAYED_PERIOD', 'Delayed Period'), ('HIGH_GLYCEMIA', 'High Glycemia'), ('LOW_GLYCEMIA', 'Low Glycemia'), ('HIGH_BLOOD_PRESSURE', 'High Blood Pressure'), ('LOW_BLOOD_PRESSURE', 'Low Blood Pressure'), ('APPOINTMENT_REMINDER', 'Appointment Reminder'), ('TREATMENT_REMINDER', 'Treatment Reminder'), ('ULTRASOUND_REMINDER', 'Ultrasound Reminder'), ('MEDICATION_REMINDER', 'Medication Reminder'), ('RISK_HIGH', 'High Risk Detected'), ('RISK_MEDIUM', 'Medium Risk Detected'), ('PERSONAL_SPIKE', 'Unusual Personal Reading')], max_length=50),
        ),
    ]
