# Generated by Django 6.0.2 on 2026-03-08 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_rename_status_alert_status_alert_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='level',
            field=models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='INFO', max_length=30),
        ),
    ]
