# Generated by Django 6.0.2 on 2026-03-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alert_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('HEALTH', 'Health alert triggered by measurements or ML risk assessment'), ('REMINDER', 'Reminder for appointments, medication, or treatment'), ('DOCTOR_MESSAGE', 'Manual message or instruction sent by a doctor'), ('SYSTEM', 'System alert such as inactivity or pregnancy milestones')], max_length=50),
        ),
    ]
