# Generated by Django 6.0.2 on 2026-03-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alter_alert_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
