# Generated by Django 6.0.2 on 2026-03-12 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_alert_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='is_read',
        ),
    ]
