# Generated by Django 6.0.2 on 2026-05-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_remove_alert_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('READ', 'Read'), ('RESOLVED', 'Resolved')], default='NEW', max_length=30),
        ),
    ]
