name: frontend
description: "Medical Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # ── Navigation ──
  go_router: ^14.2.0                  # like react-router-dom

  # ── State Management ──
  flutter_riverpod: ^2.5.1            # like Redux / Context API

  # ── HTTP Client ──
  dio: ^5.4.3                         # like axios

  # ── Secure Storage (for JWT tokens) ──
  flutter_secure_storage: ^9.2.2      # store tokens safely

  # ── Models / JSON ──
  freezed_annotation: ^2.4.1          # immutable models
  json_annotation: ^4.9.0             # JSON serialization

  # ── UI ──
  carousel_slider: ^4.2.1             # carousel
  cached_network_image: ^3.3.1        # load & cache images from API

  # ── Utils ──
  intl: ^0.19.0                       # date formatting

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # ── Code Generators (run: dart run build_runner build) ──
  freezed: ^2.5.2                     # generates model boilerplate
  json_serializable: ^6.8.0           # generates fromJson/toJson
  build_runner: ^2.4.9                # runs the generators

flutter:
  uses-material-design: true