// test/widget_test.dart
// The default counter smoke test generated by `flutter create` has been
// replaced. App-level widget tests live in test/features/auth/.

import 'package:flutter_test/flutter_test.dart';

void main() {
  test('placeholder — see test/features/auth/ for widget tests', () {
    expect(true, isTrue);
  });
}
