# Generated by Django 6.0.2 on 2026-03-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_doctor_alter_appointment_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
