# Generated by Django 6.0.2 on 2026-04-03 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_alter_patient_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('commercial_name', models.CharField(blank=True, max_length=100, null=True)),
                ('form', models.CharField(blank=True, max_length=50, null=True)),
                ('dosage', models.CharField(blank=True, max_length=50, null=True)),
                ('package', models.CharField(blank=True, max_length=50, null=True)),
                ('public_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tarif_reference', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.CharField(choices=[('V', 'vital'), ('E', 'essential'), ('I', 'Intermediate importance'), ('N', 'non-essential')], max_length=1)),
                ('DCI', models.TextField()),
                ('prior_approval', models.CharField(choices=[('O', 'need doctor or pharmacist approval'), ('N', 'no doctor approval needed')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('dose', models.CharField(max_length=255)),
                ('frequency', models.CharField(max_length=255)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatments', to='medications.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_time', models.TimeField()),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='medications.treatment')),
            ],
        ),
    ]
