# Generated by Django 6.0.2 on 2026-03-03 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pregnancies', '0002_alter_pregnancy_patient'),
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatments', to='medications.medication'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='pregnancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='Pregnancies.pregnancy'),
        ),
    ]
