# Generated by Django 6.0.2 on 2026-04-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medication',
            old_name='DCI',
            new_name='dci',
        ),
        migrations.AlterField(
            model_name='medication',
            name='public_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='tarif_reference',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
