# Generated by Django 6.0.2 on 2026-04-04 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dci', '0001_initial'),
        ('medications', '0002_rename_dci_medication_dci_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationDci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dci_medications', to='dci.dci')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_dcis', to='medications.medication')),
            ],
            options={
                'unique_together': {('medication', 'dci')},
            },
        ),
    ]
