# Generated by Django 6.0.2 on 2026-03-08 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0003_remove_treatment_pregnancy_treatment_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_time', models.TimeField()),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='medications.treatment')),
            ],
        ),
    ]
