# Generated by Django 6.0.2 on 2026-04-08 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0004_trigram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='medications.medication'),
        ),
    ]
