# Generated by Django 6.0.2 on 2026-03-08 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0004_treatmentschedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medication',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='treatment',
            old_name='dosage',
            new_name='dose',
        ),
    ]
