# Generated by Django 6.0.2 on 2026-05-01 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0005_alter_treatment_medication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='category',
            field=models.CharField(blank=True, choices=[('V', 'vital'), ('E', 'essential'), ('I', 'Intermediate importance'), ('N', 'non-essential')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='prior_approval',
            field=models.CharField(blank=True, choices=[('O', 'need doctor or pharmacist approval'), ('N', 'no doctor approval needed')], max_length=1, null=True),
        ),
    ]
