# Generated by Django 6.0.2 on 2026-05-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0006_alter_medication_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='dosage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='form',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='package',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
