# Generated by Django 6.0.2 on 2026-05-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0007_alter_medication_dosage_alter_medication_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
