# Generated by Django 6.0.2 on 2026-03-02 05:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+$')])),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(choices=[('TUNIS', 'Tunis'), ('ARIANA', 'Ariana'), ('BEN_AROUS', 'Ben Arous'), ('MANOUBA', 'Manouba'), ('NABEUL', 'Nabeul'), ('ZAGHOUAN', 'Zaghouan'), ('BIZERTE', 'Bizerte'), ('BEJA', 'Béja'), ('JENDOUBA', 'Jendouba'), ('KEF', 'Le Kef'), ('SILIANA', 'Siliana'), ('SOUSSE', 'Sousse'), ('MONASTIR', 'Monastir'), ('MAHDIA', 'Mahdia'), ('SFAX', 'Sfax'), ('KAIROUAN', 'Kairouan'), ('KASSERINE', 'Kasserine'), ('SIDI_BOUZID', 'Sidi Bouzid'), ('GABES', 'Gabès'), ('MEDENINE', 'Médenine'), ('TATAOUINE', 'Tataouine'), ('GAFSA', 'Gafsa'), ('TOZEUR', 'Tozeur'), ('KEBILI', 'Kébili')], default='TUNIS', max_length=20)),
                ('address', models.TextField()),
                ('experience', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('consultation_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('bio', models.TextField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doctors.speciality')),
            ],
        ),
    ]
