# Generated by Django 6.0.2 on 2026-05-03 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctorschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='is_available',
        ),
    ]
