# Generated by Django 6.0.2 on 2026-05-03 03:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_remove_doctor_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='consultation_duration',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
