# Generated by Django 6.0.2 on 2026-05-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_alter_doctor_latitude_alter_doctor_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=11, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=11, max_digits=11, null=True),
        ),
    ]
