# Generated by Django 6.0.2 on 2026-03-03 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pregnancies', '0001_initial'),
        ('patients', '0002_alter_patient_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregnancy',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancy', to='patients.patient'),
        ),
    ]
