// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6d68JHKJf-zHrxgdlnMmbEwTxNwXmOWk',
    appId: '1:234218707987:android:45314de1c7adb3ada5f3e6',
    messagingSenderId: '234218707987',
    projectId: 'sahhty-c4542',
    storageBucket: 'sahhty-c4542.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKLK54O_kUr1KYH0D3288vNpZWF7RbVM8',
    appId: '1:234218707987:ios:56c318cd002c85b1a5f3e6',
    messagingSenderId: '234218707987',
    projectId: 'sahhty-c4542',
    storageBucket: 'sahhty-c4542.firebasestorage.app',
    iosBundleId: 'com.example.sahhty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKLK54O_kUr1KYH0D3288vNpZWF7RbVM8',
    appId: '1:234218707987:ios:56c318cd002c85b1a5f3e6',
    messagingSenderId: '234218707987',
    projectId: 'sahhty-c4542',
    storageBucket: 'sahhty-c4542.firebasestorage.app',
    iosBundleId: 'com.example.sahhty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuf19eZ-VfuRK3xKiwYFO3NTF221wsAEo',
    appId: '1:234218707987:web:c084d52b17aa66d3a5f3e6',
    messagingSenderId: '234218707987',
    projectId: 'sahhty-c4542',
    authDomain: 'sahhty-c4542.firebaseapp.com',
    storageBucket: 'sahhty-c4542.firebasestorage.app',
    measurementId: 'G-3JYTNVX9CF',
  );
}
