# Generated by Django 6.0.2 on 2026-04-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DCI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('overall_status', models.CharField(choices=[('SAFE', 'Safe'), ('UNSAFE', 'Unsafe'), ('UNKNOWN', 'Unknown'), ('CAUTION', 'Caution'), ('NOT_APPLICABLE', 'Not Applicable')], max_length=20)),
                ('first_trimester_status', models.CharField(choices=[('SAFE', 'Safe'), ('UNSAFE', 'Unsafe'), ('UNKNOWN', 'Unknown'), ('CAUTION', 'Caution'), ('NOT_APPLICABLE', 'Not Applicable')], max_length=20)),
                ('second_trimester_status', models.CharField(choices=[('SAFE', 'Safe'), ('UNSAFE', 'Unsafe'), ('UNKNOWN', 'Unknown'), ('CAUTION', 'Caution'), ('NOT_APPLICABLE', 'Not Applicable')], max_length=20)),
                ('third_trimester_status', models.CharField(choices=[('SAFE', 'Safe'), ('UNSAFE', 'Unsafe'), ('UNKNOWN', 'Unknown'), ('CAUTION', 'Caution'), ('NOT_APPLICABLE', 'Not Applicable')], max_length=20)),
                ('delivery_status', models.CharField(choices=[('SAFE', 'Safe'), ('UNSAFE', 'Unsafe'), ('UNKNOWN', 'Unknown'), ('CAUTION', 'Caution'), ('NOT_APPLICABLE', 'Not Applicable')], max_length=20)),
                ('summary', models.TextField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
