# Generated by Django 6.0.2 on 2026-04-07 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dci', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dci_interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('CONTRE_INDICATION', 'Contre-indication'), ('PRECAUTION_EMPLOI', "Précaution d'emploi"), ('DECONSEILLEE', 'Déconseillée'), ('A_PRENDRE_EN_COMPTE', 'À prendre en compte'), ('NON_SIGNIFICATIVE', 'Non significative')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('dci1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dci1_interactions', to='dci.dci')),
                ('dci2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dci2_interactions', to='dci.dci')),
            ],
        ),
    ]
