# Generated by Django 6.0.2 on 2026-04-07 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dci', '0002_dci_interaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dci_interaction',
            new_name='DciInteraction',
        ),
    ]
