# Generated by Django 6.0.2 on 2026-03-02 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_can_password_reset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='can_password_reset',
            new_name='can_reset_password',
        ),
    ]
