# Generated by Django 6.0.2 on 2026-04-21 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_fcmdevice'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fcmdevice',
            unique_together={('user', 'fcm_token')},
        ),
    ]
