# Generated by Django 6.0.2 on 2026-04-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_fcmdevice_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmdevice',
            name='fcm_token',
            field=models.TextField(),
        ),
    ]
