# Generated by Django 6.0.2 on 2026-05-01 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_fcmdevice_fcm_token'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fcmdevice',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='fcmdevice',
            name='fcm_token',
            field=models.TextField(unique=True),
        ),
    ]
