# Generated by Django 6.0.2 on 2026-05-01 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_fcmdevice_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmdevice',
            name='fcm_token',
            field=models.TextField(),
        ),
    ]
