# Generated by Django 6.0.2 on 2026-05-13 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_fcmdevice_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
